"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-07 03:47:56.551708
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import nexum.models.types

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "schedule", "event", "manual", name="trigger_type", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("trigger_config", sa.JSON(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("estimated_minutes_saved", sa.Integer(), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("last_run_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("next_run_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "company_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("default_weekly_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column(
            "weekly_overtime_threshold_hours", nexum.models.types.FixedPoint(), nullable=False
        ),
        sa.Column("overtime_multiplier", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("premium_rules", sa.JSON(), nullable=False),
        sa.Column("holidays", sa.JSON(), nullable=False),
        sa.Column("rounding_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_break_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_break_after_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("vacation_days_per_year", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column(
            "pay_period_type",
            sa.Enum("monthly", "biweekly", name="pay_period_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("biweekly_anchor", sa.Date(), nullable=True),
        sa.Column("email_notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("smtp_host", sa.String(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=False),
        sa.Column("smtp_username", sa.String(length=255), nullable=True),
        sa.Column("smtp_password", sa.String(length=255), nullable=True),
        sa.Column("smtp_from", sa.String(length=255), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=False),
        sa.Column("updated_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("cost_center", sa.String(length=64), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pay_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "closed", "paid", name="pay_period_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("closed_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("paid_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_date", "end_date", name="uq_pay_period_window"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "employee", name="role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("session_salt", sa.String(length=32), nullable=False),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("last_login_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)

    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("started_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("finished_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "success", "failed", "skipped", name="run_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("trigger_summary", sa.String(length=255), nullable=False),
        sa.Column("log", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("minutes_saved", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["automation_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "hourly",
                "contractor",
                name="employment_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "pay_type",
            sa.Enum("monthly", "hourly", name="pay_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("monthly_salary", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("hourly_rate", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("weekly_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("calendar_token", sa.String(length=48), nullable=False),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_token"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employees_email"), ["email"], unique=True)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="notification_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("used_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "schedule_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("role_label", sa.String(length=80), nullable=True),
        sa.Column("required_skill_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["required_skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "availability_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "unavailable", "preferred", name="availability_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employee_skills",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id", "skill_id"),
    )
    op.create_table(
        "payslips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pay_period_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("regular_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("overtime_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("premium_hours", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("base_amount", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("overtime_amount", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("premium_amount", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("adjustments_amount", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("gross_amount", nexum.models.types.FixedPoint(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("generated_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pay_period_id"], ["pay_periods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pay_period_id", "employee_id", name="uq_payslip_period_emp"),
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("starts_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("ends_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("role_label", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "published", "cancelled", name="shift_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("required_skill_id", sa.Integer(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["required_skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["schedule_templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_shifts_employee_start", ["employee_id", "starts_at"], unique=False
        )
        batch_op.create_index("ix_shifts_window", ["starts_at", "ends_at"], unique=False)

    op.create_table(
        "time_off_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "vacation",
                "sick",
                "parental",
                "unpaid",
                "other",
                name="time_off_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "cancelled",
                name="time_off_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shift_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "claim", "drop", "transfer", name="shift_request_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "cancelled",
                name="shift_request_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("target_employee_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decided_by_user_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("decision_note", sa.String(length=255), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shift_id"], ["shifts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "time_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("clock_in", nexum.models.types.UTCDateTime(), nullable=False),
        sa.Column("clock_out", nexum.models.types.UTCDateTime(), nullable=True),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "submitted",
                "approved",
                "rejected",
                name="time_entry_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", nexum.models.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shift_id"], ["shifts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # departments.manager_id -> employees.id is circular with employees.department_id
    # (use_alter=True in the model); add it once both tables exist.
    with op.batch_alter_table("departments") as batch_op:
        batch_op.create_foreign_key(
            "fk_department_manager", "employees", ["manager_id"], ["id"], ondelete="SET NULL"
        )


def downgrade() -> None:
    with op.batch_alter_table("departments") as batch_op:
        batch_op.drop_constraint("fk_department_manager", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_entries")
    op.drop_table("shift_requests")
    op.drop_table("time_off_requests")
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index("ix_shifts_window")
        batch_op.drop_index("ix_shifts_employee_start")

    op.drop_table("shifts")
    op.drop_table("payslips")
    op.drop_table("employee_skills")
    op.drop_table("availability_rules")
    op.drop_table("schedule_templates")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employees_email"))

    op.drop_table("employees")
    op.drop_table("automation_runs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("skills")
    op.drop_table("pay_periods")
    op.drop_table("departments")
    op.drop_table("company_settings")
    op.drop_table("automation_rules")
    # ### end Alembic commands ###
